### ISSUE TITLE
Whats the point of this pattern

### ISSUE THREAD

**Issue by JoNMii** [RoyVoetman/laravel-repository-pattern#1]
**Why do this:**
$book = Book::find(1);

(new BooksRepository())->delete($book);

**instead**:

$deleted = Book::find(1)->first()->delete();

**Comment by RoyVoetman** [comment]
The purpose of this package in short is: "you can add additional save/delete logic (e.g. managing your relations or manipulating data) to your models by defining pipes. This is comparable to the concept of middleware".

Your example of `$deleted = Book::find(1)->delete();` does not use the added pipeline functionality. 

A more thorough explanation is provided in the first section of the documentation:
 
"This package provides a convenient mechanism for grouping data manipulation logic, which is equivalent to Laravel's native HTTP middleware. However, to prevent any confusion with HTTP middleware hereafter this mechanism will be referred to in its more general form called a pipeline. In fact, Laravel provides its own Pipeline implementation which is used by middleware under the hood.

A pipeline is a design pattern that composes several different classes (pipes) and applies them consecutively. All pipes receive a so-called passable and result in a so-called returnable. In the context of HTTP middleware, the passable is the HTTP request object and the returnable is the HTTP response object. Conversely, in the context of a repository, the model-data array is classified as the passable and the resulting Eloquent model object is the returnable. Typically, each pipe will filter or alter the passable that is sent through the pipeline. As a result, creating an easily extensible architecture where each pipe concerns itself with one task. For example, this package provides a pipe that automatically hashes passwords before saving them to the database. Thus, centralizing your password hashing logic and thereby removing responsibility from your other classes.

Additional pipes can be written to perform a variety of tasks besides modifying column values. A translation pipe might save all translations for certain columns to a separate translations table. A transaction pipe might run specific groups of queries in a database transaction. There are a few pipes already included in this package, including pipes for password hashing and database transactions. All of these default pipes will be elaborated upon, along with information on how to define your own pipes."
